name: AuroraCraft-Parejas
version: '1.0'
main: p.zestianparejas.ZestianParejas
author: Spinnin34
commands:
  casarse:
    description: Comando para casarse con otro jugador.
    usage: /casarse <nombre>
  divorcio:
    description: Comando para divorciarse de tu pareja actual.
    usage: /divorcio
